server:
  port: 8083
spring:
  application:
    name: feign-consumer
  zipkin:
    base-url: http://localhost:9400
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutinMilliseconds: 5000
ribbon:
  connectTimeout: 500

