#端口号
server:
  port: 8011
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9400
    enabled: true
#服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10，如果不配置，有个默认的百分比的
#  sleuth:
#    sampler:
#      percentage: 0.3

eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://localhost:8001/eureka/